#!/bin/bash
# Run Cosmos Transfer 2.5 depth+edge inference on Hypersim frames.
#
# Usage:
#   bash run_hypersim_cosmos.sh [--control depth_edge] [--gpus 0,1,2,3]
#
# Output: outputs/hypersim/cosmos_<control>/
# Specs:  generated by create_hypersim_cosmos_specs.py, sharded per GPU

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COSMOS_DIR="$SCRIPT_DIR/CosmosTransfer"
IMAGE_ID="cosmos-transfer25:latest"
SPECS_DIR="/tmp/cosmos_hypersim/specs"
CONTROL="depth_edge"
GPUS="0,1,2,3"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --control) CONTROL="$2"; shift 2 ;;
        --gpus)    GPUS="$2";    shift 2 ;;
        --gpu)     GPUS="$2";    shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

controls="${CONTROL//_/ }"
out_dir="$SCRIPT_DIR/outputs/hypersim/cosmos_${CONTROL}"
mrtstorage_out="/mrtstorage/users/kwang/hypersim_cosmos_${CONTROL}"

mkdir -p "$out_dir" "$mrtstorage_out"

source "$SCRIPT_DIR/.venv/bin/activate"

# Generate full spec set if missing
if [[ ! -d "$SPECS_DIR/${CONTROL}" ]]; then
    echo "  Generating specs..."
    python "$SCRIPT_DIR/create_hypersim_cosmos_specs.py" \
        --controls $controls \
        --out_dir "$SPECS_DIR" \
        --input_dir /mrtstorage/datasets_tmp/hypersim \
        --input_dir_docker /mrtstorage/datasets_tmp/hypersim
fi

GPU_LIST=(${GPUS//,/ })
N_GPUS=${#GPU_LIST[@]}

# Shard specs across GPUs
python - <<PYEOF
import os, glob
specs = sorted(glob.glob("$SPECS_DIR/${CONTROL}/*.json"))
n, chunk = len(specs), (len(specs) + ${N_GPUS} - 1) // ${N_GPUS}
for i in range(${N_GPUS}):
    d = f"$SPECS_DIR/${CONTROL}_gpu{i}"
    os.makedirs(d, exist_ok=True)
    for s in specs[i*chunk:(i+1)*chunk]:
        dst = os.path.join(d, os.path.basename(s))
        if not os.path.exists(dst):
            os.symlink(s, dst)
    print(f"  GPU {i} ({${GPU_LIST[$i]:-unknown}}): {len(os.listdir(d))} specs")
PYEOF

echo "=== Hypersim Cosmos ${CONTROL} on ${N_GPUS} GPU(s): ${GPUS} ==="
echo "  Output: $out_dir"

run_one() {
    local gpu=$1
    local idx=$2
    local shard_dir="$SPECS_DIR/${CONTROL}_gpu${idx}"
    echo "  [GPU $gpu] starting ($(ls "$shard_dir" | wc -l) specs)..."
    docker run --rm \
        --runtime=nvidia \
        --ipc=host \
        -e CUDA_VISIBLE_DEVICES="$gpu" \
        -e HF_TOKEN="${HUGGING_FACE_TOKEN:-}" \
        -e CUDA_NAME=cu128 \
        -v "$COSMOS_DIR":/workspace \
        -v /workspace/.venv \
        -v /root/.cache:/root/.cache \
        -v "$SPECS_DIR":/staging/specs \
        -v /mrtstorage:/mrtstorage \
        -v "$out_dir":/output \
        "$IMAGE_ID" \
        bash -c "python examples/inference.py \
            -i /staging/specs/${CONTROL}_gpu${idx}/*.json \
            -o /output \
            --disable-guardrails"
    echo "  [GPU $gpu] done."
}

for idx in "${!GPU_LIST[@]}"; do
    run_one "${GPU_LIST[$idx]}" "$idx" &
done
wait

rsync -av --progress "$out_dir/" "$mrtstorage_out/"
ln -sfn "$mrtstorage_out" "$SCRIPT_DIR/outputs/hypersim/cosmos_${CONTROL}"

echo "Done. $(ls "$out_dir"/*.jpg 2>/dev/null | wc -l) images saved."
