#!/usr/bin/env bash
# Run Cosmos Transfer 2.5-2B img2img inference on vKITTI clone frames.
#
# Usage:
#   export HUGGING_FACE_TOKEN=hf_...
#   bash run_vkitti_cosmos.sh                              # all 3 combos in parallel
#   bash run_vkitti_cosmos.sh --control depth_vis --gpu 4  # single combo
#
# Control combos (img2img, one spec per frame):
#   depth_vis        — depth(1.0) + vis(0.5)
#   depth_seg        — depth(1.0) + seg(1.0)
#   depth_vis_seg    — depth(1.0) + vis(0.5) + seg(1.0)
#
# Output: outputs/vkitti/cosmos_{control}/
# Specs:  generated by create_cosmos_specs.py → /tmp/cosmos_vkitti/specs/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COSMOS_DIR="$SCRIPT_DIR/CosmosTransfer"
IMAGE_ID="sha256:95dc719d36b4af82ad0bff3ad462b5c77c3bd0eeb970596d083ecf1ae81a2931"
SPECS_DIR="/tmp/cosmos_vkitti/specs"
CONTROL=""
GPU=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --control) CONTROL="$2"; shift 2 ;;
        --gpu)     GPU="$2";     shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

run_combo() {
    local combo="$1"
    local gpu="$2"
    # combo is underscore-separated, convert to space-separated for --controls
    local controls="${combo//_/ }"

    local out_dir="$SCRIPT_DIR/outputs/vkitti/cosmos_${combo}"
    mkdir -p "$out_dir"

    echo "=== [$combo] GPU $gpu ==="

    source "$SCRIPT_DIR/.venv/bin/activate"

    if [[ ! -d "$SPECS_DIR/$combo/image" ]]; then
        echo "  Generating specs for $combo..."
        python "$SCRIPT_DIR/create_cosmos_specs.py" --mode image --controls $controls
    fi

    echo "  Specs:  $SPECS_DIR/$combo/image/*.json"
    echo "  Output: $out_dir"

    docker run --rm \
        --runtime=nvidia \
        --ipc=host \
        -e CUDA_VISIBLE_DEVICES="$gpu" \
        -e HF_TOKEN="${HUGGING_FACE_TOKEN:-}" \
        -e CUDA_NAME=cu128 \
        -v "$COSMOS_DIR":/workspace \
        -v /workspace/.venv \
        -v /root/.cache:/root/.cache \
        -v "$SPECS_DIR":/staging/specs \
        -v /mrtstorage:/mrtstorage \
        -v "$out_dir":/output \
        "$IMAGE_ID" \
        bash -c "python examples/inference.py \
            -i /staging/specs/$combo/image/*.json \
            -o /output \
            --disable-guardrails"

    echo "  Done. $(ls "$out_dir"/*.jpg 2>/dev/null | wc -l) images saved to $out_dir/"
}

if [[ -n "$CONTROL" && -n "$GPU" ]]; then
    # Single combo specified
    run_combo "$CONTROL" "$GPU"
elif [[ -z "$CONTROL" && -z "$GPU" ]]; then
    # Launch all 3 combos in parallel
    echo "Launching 3 combos in parallel..."
    run_combo depth_vis     4 &
    run_combo depth_seg     5 &
    run_combo depth_vis_seg 7 &
    wait
    echo ""
    echo "All combos done."
else
    echo "Error: provide both --control and --gpu, or neither (runs all 3)"
    exit 1
fi
